PROJECT-SUNDO/sundo

pom.xml, src/main/resources/static/common/css/style.css, src/main/resources/static/front/css/style.css, src/main/resources/static/front/js/map/map.js, src/main/webapp/WEB-INF/templates/front/map/map.html
1. 지도 축적 크기 고정해야함
2. 거리 측정 오류 수정해야함
- 처음은 측정 가능, 그 이후 수치 안뜸
- 한번 측정 후 계속 측정됨
=> feat: 지도 축적 표시, 전체버튼 활성화, 거리 측정 추가

src/main/java/org/sundo/list/repositories/ObservatoryRepository.java, src/main/webapp/WEB-INF/templates/front/list/list.html
list: 관측소 정보 template 수정 및 관측소 repository 생성
=> feat:  관측소 repository 생성

pom.xml, src/main/java/org/sundo/configs/BeanConfig.java, src/main/java/org/sundo/list/entities/Observatory.java, src/main/java/org/sundo/list/repositories/ObservatoryRepository.java, src/main/java/org/sundo/wamis/constants/ApiURL.java, src/main/java/org/sundo/wamis/controllers/ApiWamisController.java, src/main/java/org/sundo/wamis/entities/Observatory.java, src/main/java/org/sundo/wamis/entities/ObservatoryId.java, src/main/java/org/sundo/wamis/entities/WaterFlowLevel.java, src/main/java/org/sundo/wamis/entities/WaterFlowLevelId.java, src/main/java/org/sundo/wamis/entities/WaterLevel.java, src/main/java/org/sundo/wamis/entities/WaterLevelId.java, src/main/java/org/sundo/wamis/repositories/ObservatoryRepository.java, src/main/java/org/sundo/wamis/repositories/WaterFlowLevelRepository.java, src/main/java/org/sundo/wamis/repositories/WaterLevelRepository.java, src/main/java/org/sundo/wamis/services/ApiResult.java, src/main/java/org/sundo/wamis/services/ApiResultList.java, src/main/java/org/sundo/wamis/services/WamisApiService.java
=> feat: 관측소, 수위, 유량 api 

src/main/java/org/sundo/wamis/constants/ApiURL.java, src/main/java/org/sundo/wamis/entities/Precipitation.java, src/main/java/org/sundo/wamis/entities/PrecipitationId.java, src/main/java/org/sundo/wamis/repositories/PrecipitationRepository.java, src/main/java/org/sundo/wamis/services/WamisApiService.java, src/main/java/org/sundo/wamis/services/WamisSchedulingService.java
feat: 강수량에 관한 API 기능 추가
- 설명 : 
강수량 api 추가에 관한 entity, repository,service 기능 추가
=> feat: 강수량에 관한 API 기능 추가

src/main/java/org/sundo/wamis/constants/ObservType.java
feat : 관측소 enum 클래스
- 설명
강수량, 수위, 유량, cctv에 대한  enum 클래스
=> feat : 관측소 enum 클래스

src/main/java/org/sundo/wamis/constants/ApiURL.java, src/main/java/org/sundo/wamis/controllers/ApiWamisController.java, src/main/java/org/sundo/wamis/entities/Precipitation.java, src/main/java/org/sundo/wamis/repositories/PrecipitationRepository.java, src/main/java/org/sundo/wamis/services/WamisApiService.java
feat : 강수량 데이터 API받아오기
- 설명
강수량 데이터 받아오기
- 엔티티
- 서비스
- 레포지토리
=> feat : 강수량 데이터 API받아오기

src/main/resources/static/front/js/dashboard/dashboard.js, src/main/webapp/WEB-INF/templates/front/dashboard/dashboard.html, src/main/webapp/WEB-INF/templates/front/layouts/main.html, src/main/webapp/WEB-INF/templates/front/outlines/header.html
=> feat: 대쉬보드 테스트 차트

src/main/java/org/sundo/commons/Utils.java, src/main/java/org/sundo/commons/exceptions/AlertBackException.java, src/main/java/org/sundo/commons/exceptions/AlertException.java, src/main/java/org/sundo/commons/exceptions/CommonException.java, src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/controllers/ObservatoryValidator.java, src/main/java/org/sundo/list/controllers/RequestObservatory.java, src/main/java/org/sundo/list/services/ListDeleteService.java, src/main/java/org/sundo/list/services/ListSaveService.java, src/main/java/org/sundo/list/services/ObservatoryDataNotFoundException.java, src/main/java/org/sundo/wamis/entities/Observatory.java, src/main/java/org/sundo/wamis/repositories/ObservatoryRepository.java, src/main/resources/messages/validations.properties, src/main/resources/static/front/js/common.js, src/main/webapp/WEB-INF/templates/front/list/_form.html, src/main/webapp/WEB-INF/templates/front/list/update.html, src/main/webapp/WEB-INF/templates/front/list/write.html
- feat :  list 등록/수정 기능 구현
- 등록 /수정
- 1차 등록
- 엔티티,controller, 서비스
=> feat :  list 등록/수정 기능 구현

src/main/java/org/sundo/commons/Utils.java, src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/services/ListSaveService.java, src/main/java/org/sundo/list/services/ObservatoryDataNotFoundException.java
fix : list 충돌 오류 수정
- 설명 :  깃 충돌 해결
=> fix : list 충돌 오류 수정

src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/services/ListSaveService.java, src/main/java/org/sundo/wamis/repositories/ObservatoryRepository.java
=> feat : list 기능 추가

src/main/webapp/WEB-INF/templates/front/map/map.html
=> feat: 버튼 중복 삭제

src/main/java/org/sundo/list/controllers/ListController.java
=> feat: 리스트 서비스관련 코드 삭제

pom.xml, src/main/java/org/sundo/configs/SecurityConfig.java, src/main/webapp/WEB-INF/web.xml
setting: security 의존성 추가 및 무력화
=> mamber -> dev / setting: security 의존성 추가 및 무력화

src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/controllers/ObservatoryValidator.java, src/main/java/org/sundo/wamis/repositories/ObservatoryRepository.java, src/main/webapp/WEB-INF/templates/front/list/delete.html, src/main/webapp/WEB-INF/templates/front/list/list.html, src/main/webapp/WEB-INF/templates/front/list/update.html
=> feat : list 수정 2차 수정

src/main/java/org/sundo/list/controllers/ListController.java, src/main/webapp/WEB-INF/templates/front/list/list.html
feat : delete  1차 완료
설명 : 삭제 팝업 버튼 1차 완료 입니다.
=> feat : delete  1차 완료

src/main/java/org/sundo/wamis/services/ObservatoryDataDelete.java
feat : delete 1차 완료
- 설명
- 리스트 메인페이지에서 리스트 목록 삭제
- 삭제 기능은 완성 했지만 디자인은 선생님께서 보완 방법을 알려주셔야함.
=> feat : delete 1차 완료

src/main/java/org/sundo/wamis/services/ObservatoryInfoService.java, src/main/java/org/sundo/wamis/services/ObservatoryNotFoundException.java, src/main/webapp/WEB-INF/templates/front/list/_form.html
design : list 목록 수정 완료
설명
수정시 오류나는 데이터 수정 
#close 완료
=> design : list 목록 수정 완료

.idea/jarRepositories.xml, .idea/misc.xml, src/main/resources/static/common/js/common.js, src/main/resources/static/front/js/dashboard/dashboard.js, src/main/webapp/WEB-INF/templates/front/dashboard/dashboard.html, src/main/webapp/WEB-INF/templates/front/layouts/main.html
=> feat: 대쉬보드 테스트 차트 수정중

src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/controllers/StatisticSearch.java, src/main/java/org/sundo/wamis/entities/Statistic.java, src/main/java/org/sundo/wamis/services/StatisticInfoService.java, src/main/webapp/WEB-INF/templates/error/400.html, src/main/webapp/WEB-INF/templates/error/401.html, src/main/webapp/WEB-INF/templates/error/403.html, src/main/webapp/WEB-INF/templates/error/404.html, src/main/webapp/WEB-INF/templates/error/405.html, src/main/webapp/WEB-INF/templates/error/_content.html, src/main/webapp/WEB-INF/templates/error/common.html, src/main/webapp/WEB-INF/templates/front/list/info.html
=> design: 관측 정보

pom.xml, src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/controllers/ObservatoryValidator.java, src/main/java/org/sundo/list/controllers/RequestObservatory.java, src/main/java/org/sundo/wamis/services/ObservatoryDeleteService.java, src/main/resources/messages/validations.properties
feat : 유효성 2차
list 등록 유효성 
1. 글자 길이
2.  빈칸
=> feat : 유효성 2차

src/main/java/org/sundo/wamis/services/WamisApiService.java
- addr에 서울, 경기도 포함한 관측소만 저장
- addr이 존재하는 관측소만 저장
=> feat: 관측소 필터링

src/main/resources/static/common/css/style.css, src/main/resources/static/front/js/map/map.js, src/main/resources/static/front/js/map/markers.js, src/main/webapp/WEB-INF/templates/front/layouts/main.html, src/main/webapp/WEB-INF/templates/front/map/map.html
map_je -> map : 저장 버튼 완/ 마커 좌표계수정필요
=> map_je -> map : 저장 버튼 완/ 마커 좌표계수정필요

pom.xml, src/main/java/org/sundo/commons/Excel.java
feat : 엑셀 의존성과 코드
설명
pom.xml에 poi 의존성 추가
common에 excel코드 추가
=> feat : 엑셀 의존성과 코드

src/main/webapp/WEB-INF/templates/front/list/write.html
=> feat :  등록버튼 오류수정

src/main/resources/static/front/css/list/style.css, src/main/webapp/WEB-INF/templates/front/list/_form.html, src/main/webapp/WEB-INF/templates/front/list/write.html
=> design : 목록 css 입히기 1차

src/main/java/org/sundo/list/controllers/ListController.java, src/main/resources/static/front/css/list/style.css, src/main/webapp/WEB-INF/templates/front/list/update.html
design : list css 완료
list css 완료
=> design : list css 완료

src/main/java/org/sundo/map/controllers/MapController.java, src/main/resources/static/front/js/map/markers.js, src/main/webapp/WEB-INF/templates/front/map/popup/cctv.html
[feat: cctv 팝업 출력](https://github.com/PROJECT-SUNDO/sundo/commit/8624b32d571b3d27912ee1c2c36a65f02f7288b4)
=> feat: cctv 팝업 출력

src/main/java/org/sundo/map/controllers/MapController.java, src/main/resources/static/common/css/style.css, src/main/resources/static/common/js/layer.js, src/main/resources/static/front/css/list/style.css, src/main/resources/static/front/js/map/markers.js, src/main/webapp/WEB-INF/templates/front/map/aside.html, src/main/webapp/WEB-INF/templates/front/map/map.html, src/main/webapp/WEB-INF/templates/front/map/popup/cctv.html
map_je -> map : 관측소명선택지도이동:완/ 마커마우스포인터적용
=> map_je -> map : 관측소명선택지도이동:완/ 마커마우스포인터적용

src/main/resources/static/common/js/api.js, src/main/resources/static/front/css/list/style.css, src/main/webapp/WEB-INF/templates/front/list/info.html, src/main/webapp/WEB-INF/templates/front/list/update.html, src/main/webapp/WEB-INF/templates/front/list/write.html
feat : 엑셀 저장 3차 오류수정
설명
엑셀저장 강수량/수위/유량 데이터 확인
엑셀저장 10분/1시간/1일/한달/1년 데이터 확인
=> feat : 엑셀 저장 3차 오류수정

src/main/resources/static/common/js/layer.js, src/main/resources/static/front/js/map/cctv.js, src/main/resources/static/front/js/map/map.js, src/main/resources/static/front/js/map/markers.js, src/main/webapp/WEB-INF/templates/front/map/aside.html, src/main/webapp/WEB-INF/templates/front/map/map.html
[perform : 저장 버튼 수정](https://github.com/PROJECT-SUNDO/sundo/commit/3aa35445e45dfb1b3833be226020c657d9597e1b)
=> perform : 저장 버튼 수정

src/main/resources/static/common/js/api.js
=> feat :10분 데이터 수정

src/main/webapp/WEB-INF/templates/front/list/update.html, src/main/webapp/WEB-INF/templates/front/list/write.html
=> design : css 완료

src/main/java/org/sundo/main/controllers/MainController.java
=> feat : 메인페이지

src/main/resources/static/common/css/popup_style.css, src/main/resources/static/front/css/list/style.css
css :  3차 완료
설명
수정/상세보기 css 변경
=> css :  3차 완료

src/main/resources/static/front/css/list/style.css, src/main/webapp/WEB-INF/templates/front/list/_form.html
=> design : css 수정

src/main/java/org/sundo/list/controllers/ListController.java, src/main/java/org/sundo/list/controllers/ObservatoryValidator.java, src/main/java/org/sundo/list/controllers/RequestObservatory.java, src/main/resources/static/common/css/style.css, src/main/webapp/WEB-INF/templates/front/list/_form.html
=> feat: 유효성 수정
